port: '6002'
application: "My Service"
instance: "main"
service:
  name: "MyService"
  display: "My Service"
log:
  youlog:
    application: "My Service"
    instance: "main"
    engine:
      local:
        type: logrus