port: '6005'
application: "My Service"
instance: "main"
staticpath: './static'
htmlsource: './static/index.html'
apiproxy:
  enable: false
  proxy: 'http://localhost:3000'
  prefix: '/api'
  rewrite: true
service:
  name: "MyService"
  display: "My Service"
log:
  youlog:
    application: "My Service"
    instance: "main"
    engine:
      local:
        type: logrus